### Header material ---------
### Final set of analyses for microbe/competition theory MS
### Gaurav Kandlikar, gaurav.kandlikar@gmail.com
### Last edit: 18 April 2019  

### This file generates Figure S5.1 for Appendix S5 of the manuscript.  
# Note: The code here is similar to the code in figure_4.R.

# Relative influence of Microbes and Resource competition on Fitness Differences
rm(list = ls())
library(tidyverse)

source("figures_and_tables/core-functions.R")
# Make a vector of numbers from 10^-1.5 to 10^1.5,
# log-distributed.
# This vector will get used to set the values of resource replacement
# rate, to simulate a fertility gradient.
itervec <- emdbook::lseq(from = 10^-1.5, to = 10^1.5, length.out = 1000)
rhos_vec <- numeric(length(itervec))
fitdiff <- numeric(length(itervec))
fitdiff_c <- numeric(length(itervec))
fitdiff_m <- numeric(length(itervec))

rhos_c_vec <- numeric(length(itervec))
rhos_m_vec <- numeric(length(itervec))

# In each iteration of the following for-loop, 
# the parameter values are identical, except for the value of 
# r_l and r_n, which define the low-density growth rate of the 
# two resources r and l. 
# The net niche overlap and fitness difference, as well as
# the SND and FD generated by competition alone or microbes alone
# are saved.

# The parameter values are almost identical to those in Figure 4,
# except that the m_2A and m_2B terms are modified to explore
# variation in fitness differences.
for (ii in 1:length(itervec)) {
  
  parameter_vector <- c(u1l = .01*.2, u1n = .001*.2,
                        u2l = .01*.2, u2n = .001*.2,
                        mu1 = .001, mu2 = .001,
                        rl = itervec[ii], rn = itervec[ii],
                        s_l = .001, s_n = .001,
                        
                        m1A = -.005, m1B = -.0048,
                        m2A = -.005*.75, m2B = -.0048*.75,
                        
                        vA1 = 0.005, vA2 = 0, vB1 = 0, vB2 = 0.005,
                        qA = .005, qB = .005)
  outcome <- do.call(predict_interaction_outcome_RC, as.list(parameter_vector))
  rhos_vec[ii]<- outcome$rho
  fitdiff[ii]<- outcome$fitness_ratio
  fitdiff_c[ii]<- outcome$fitness_ratio_comp
  fitdiff_m[ii]<- outcome$fitness_ratio_micr
  
  rhos_c_vec[ii] <- outcome$rho_comp
  rhos_m_vec[ii] <- outcome$rho_micr
}

relative_fx_1 <- data.frame(resource_replacement = itervec,
                            rho = rhos_vec,
                            rho_comp = rhos_c_vec,
                            rho_micr = rhos_m_vec,
                            fitdiff_c = fitdiff_c, 
                            fitdiff_m = fitdiff_m,
                            fitdiff = fitdiff)
relative_fx_1 <- gather(relative_fx_1, which, value, fitdiff, fitdiff_m, fitdiff_c)

figure_S5.1 <- ggplot(relative_fx_1) +
  geom_line(aes(y = value, x = resource_replacement, col = which, size = which)) +
  scale_color_manual(values = c('black',"grey25", "grey25")) + 
  scale_size_manual(values = c(1,.5,.5)) + 
  scale_x_log10() + 
  theme_gsk() +
  annotate("text", x = 10^-1.5, y = 1.325, hjust = 0, 
           label = "Microbial fitness difference", size = 3.5) +
  annotate("text", x = 10^1.5, y = 1.01, hjust = 1,
           label = "Resource use fitness difference", size = 3.5) +
  annotate("text", x = 1.35, y = 1.15, hjust = 0,
           label = "Net fitness\ndifference", size = 5, fontface = "bold.italic") +
  theme(legend.position = "none") +
  ylab(latex2exp::TeX("$\\kappa_2/\\kappa_1$")) + 
  xlab(latex2exp::TeX("Resource replacement rates ($r_l$)")) + 
  theme(axis.title = element_text(size = 15),
        axis.text = element_text(size = 11)) 

# Save image as PDF
ggsave(filename = "figures_and_tables/figures/figure_S5.1.pdf", plot = figure_S5.1, 
       height = 6, width = 6, units = "in")


