### Header material ---------
### Final set of analyses for microbe/competition theory MS
### Gaurav Kandlikar, gaurav.kandlikar@gmail.com
### Last edit: 18 April 2019  

### This file generates Figure 4 for the manuscript.  
rm(list = ls())

library(tidyverse)
library(magick)
# also requires the package emdbook (install.packages("emdbook"))

source("figures_and_tables/core-functions.R")

# Make a vector of numbers from 10^-1.5 to 10^1.5,
# log-distributed.
# This vector will get used to set the values of resource replacement
# rate, to simulate a fertility gradient.
itervec <- emdbook::lseq(from = 10^-1.5, to = 10^1.5, length.out = 1000)

# Make empty vectors to hold the output from a for-loop that iterates over itervec
rhos_vec <- numeric(length(itervec))
fitdiff <- numeric(length(itervec))
rhos_c_vec <- numeric(length(itervec))
rhos_m_vec <- numeric(length(itervec))


# In each iteration of the following for-loop, 
# the parameter values are identical, except for the value of 
# r_l and r_n, which define the low-density growth rate of the 
# two resources r and l. 
# The net niche overlap and fitness difference, as well as
# the SND and FD generated by competition alone or microbes alone
# are saved.
for (ii in 1:length(itervec)) {
  parameter_vector <- c(u1l = .01, u1n = .001,
                        u2l = .001, u2n = .01,
                        el = .04, en = .04,
                        mu1 = .001, mu2 = .001,
                        rl = itervec[ii], rn = itervec[ii],
                        alpha_l = .001, alpha_n = .001,
                        
                        m1A = -.005, m1B = -.0048,
                        m2A = -.0048, m2B = -.005,

                        vA1 = 0.005, vA2 = 0, vB1 = 0, vB2 = 0.005,
                        qA = .005, qB = .005)
  outcome <- do.call(predict_interaction_outcome_RC, as.list(parameter_vector))
  rhos_vec[ii]<- outcome$rho
  fitdiff[ii]<- outcome$fitness_ratio
  
  rhos_c_vec[ii] <- outcome$rho_comp
  rhos_m_vec[ii] <- outcome$rho_micr
  
}

# Comebine the vectors generated in the preceding for-loop into a 
# single data frame, and then reshape the dataframe.
relative_fx_1 <- data.frame(resource_replacement = itervec,
                            rho = rhos_vec,
                            rho_comp = rhos_c_vec,
                            rho_micr = rhos_m_vec,
                            fitdiff = fitdiff)
relative_fx_1 <- gather(relative_fx_1, which, value, rho, rho_micr, rho_comp)

# Make a plot using the dataframe above.
figure_4b <- ggplot(relative_fx_1) +
  geom_line(aes(y = value, x = resource_replacement, col = which, size = which)) +
  scale_color_manual(values = c('black',"grey25", "grey25")) + 
  scale_size_manual(values = c(1,.5,.5)) + 
  scale_x_log10() + 
  theme_gsk() +
  annotate("text", x = 10^-1.5, y = .985, hjust = 0,
           label = "Microbial niche overlap", size = 12) + 
  annotate("text", x = 10^1.5, y = .22, hjust = 1,
           label = "Resource use niche overlap", size = 12) + 
  annotate("text", x = 1.5, y = .6, hjust = 0,
           label = "Net niche\noverlap", size = 15, fontface = "bold.italic") + 
  theme(legend.position = "none") +
  ylab(latex2exp::TeX("Niche overlap ($\\rho$)")) + 
  xlab(latex2exp::TeX("Resource replacement rates ($r_l$)")) + 
  labs(tag = "B") + 
  theme(axis.title = element_text(size = 35),
        axis.text = element_text(size = 25),
        title = element_text(size = 25)) 

# NOTE! In the manuscript, this figure_4b generated above is combined with a 
# cartoon diagram of the model made outside of R.

# Save the image as a PDF:
ggsave(filename = "figures_and_tables/figures/figure-4b.pdf", plot = figure_4b, height = 12, width = 12)

# Combine the two files (figure-4a.pdf and figure-4b.pdf) into one using a system call to pdfjam.
# The following commented line only works provided the file paths are accurate.

system("pdfjam ~/grad/manuscripts/kandlikar-etal-psf-theory/figures_and_tables/figures/figure-4a.pdf ~/grad/manuscripts/kandlikar-etal-psf-theory/figures_and_tables/figures/figure-4b.pdf --nup 2x1 --landscape --outfile ~/grad/manuscripts/kandlikar-etal-psf-theory/figures_and_tables/figures/figure-4.pdf")
